### ISSUE TITLE
Merge v3 into master

### ISSUE THREAD

**Issue by lthibault** [capnproto/go-capnproto2#172]
As per previous discussion in #165, I am opening this issue to track discussion about merging `v3` into `master`.

**General Overview**

Our approach is motivated by the fact that 

1. `go-capnproto2` uses SemVer tagging
2. Go module tooling is both git tag and SemVer aware
3. #169 adds Go module support for v3

Taken together, these remove the need to enforce backwards-compatibility on the `master` branch.
To put it plainly:  users can now use standard module tooling to pin their dependencies to a major version (_e.g._ v2), and be unaffected by breaking changes pushed to `master`.

The README in `v3` has been updated to reflect these guarantees.

**Approach**

After discussing with @zenhack, we have settled on the following approach:

- [x] Tag the current tip of `master` with a final version-2 tag (`v2.18.1`)
- [x] Create a `v2` branch for archival and (if required) patch purposes
- [x] Rebase `v3` onto `master`.
- [x] Tag the new tip of `master` with `v3.0.0-alpha.1` to denote its unstable state.

Because the rebase step is fairly complex and will require some manual merging, I have derived a `feature/v3` branch from `master` as a staging branch.  Once stabilized, I will open a PR to merge `feature/v3` into master.  While not strictly necessary, this is a belt-and-suspenders thing.

Comments are of course welcome.

**Comment by lthibault** [comment]
@taylorjdawson and I are encountering a particularly tricky rebase, due mostly to the fact that we don't technically want to merge the `master` and `v3`.  Instead, we want to do something closer to:

1. Rename `master` to `v2`
2. Rename `v3` to `master`

Step one has already been performed.  I think step 2 should be a straightforward matter of:

1. `git branch -D master`
2. `git branch -m v3 master`
3. `git push -uf origin master`

Users can continue to use git tags as expected.

Does that sound good?
cc @zenhack

**Comment by zenhack** [comment]
Makes sense to me. If we wanted to avoid destructive updates to `master` (and thus the need to `-D`), we could take the opportunity to switch the default branch to `main`, as is now the github default.

**Comment by lthibault** [comment]
I'm quite wary of potential for confusion in having both `master` and `main`.  For example, I imagine a number of tools track `master` by default, leading to unexpected situations. 

The current `master` is backed up in `v2` too, so I'm personally not overly worried about the destructive updates.

Is it okay if I proceed or is the destructive update a blocking point for you?

**Comment by zenhack** [comment]
Quoting Louis Thibault (2021-05-14 17:20:12)

> Is it okay if I proceed or is the destructive update a blocking point
> for you?

Go for it.

-Ian

**Comment by lthibault** [comment]
```
$ git push -uf origin master
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Cannot force-push to this protected branch
To github.com:capnproto/go-capnproto2.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:capnproto/go-capnproto2.git'
```

@zenhack @zombiezen I'm guessing this is some kind of permission I don't have?  Could you give me these superpowers?

**Comment by zenhack** [comment]
I assume there's a setting to allow/deny force-push on branches, but I don't seem to have access to the settings pannel, so @zombiezen will have to do it.

**Comment by zombiezen** [comment]
Done.

**Comment by lthibault** [comment]
@zombiezen Thanks!  I'm still getting the same error, however, so I went ahead and renamed the branch to `main` and pushed it to `origin`.

I don't seem to have permission to change the default branch, though.  Could you grant that to me as well?

cc @zenhack (in case you have the requisite permissions)

**Comment by zenhack** [comment]
Let's keep the existing master on a `v2` branch, but I agree keeping it as `master` is likely to cause confusion.

**Comment by zenhack** [comment]
(I do not appear to have the ability to change the default branch)

**Comment by lthibault** [comment]
> Let's keep the existing master on a `v2` branch, but I agree keeping it as `master` is likely to cause confusion.

The `v2` branch is currently in sync with `master`.  This is what you mean, right?

**Comment by zenhack** [comment]
Yes.

**Comment by lthibault** [comment]
@zombiezen Any chance you might consider making Ian and I repository owners?  This way we don't have to spam you with this kind of thing in the future.

**Comment by zombiezen** [comment]
Done.
